[package]
name = "xtd"
version = "0.3.0"
authors = ["nylanderdev <rasmus.s.nylander@gmail.com>"]
edition = "2018"
license = "MIT"
description = "An extended utility library"
repository = "https://github.com/nylanderdev/xtd"
