[package]
name = "xtd"
version = "0.2.0"
authors = ["nylanderdev <rasmus.s.nylander@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
